### ISSUE TITLE
Select Body Not Working

### ISSUE THREAD

**Issue by mohdrais** [mfasano727/MBDynFCwb#10]
Dear Sir, Happy New Year
When I click on the SELECT BODY icon, nothing happens. In the Report View, it display 
"16:22:18  Running the Python command 'body_sel_cmd' failed:
Traceback (most recent call last):
  File "D:\FreeCAD_0.19.23463\Mod\MBDyn\MBDyn_guitools\body_AS4_cmd.py", line 47, in Activated
    if check_solid(modbod_sub):
  File "D:\FreeCAD_0.19.23463\Mod\MBDyn\MBDyn_utilities\MBDyn_funcs.py", line 206, in check_solid
    if sol_obj.Shape.ShapeType == 'Solid' or sol_obj.Shape.ShapeType == 'Compound':

cannot determine type of null shape

**Comment by mfasano727** [comment]
> Dear Sir, Happy New Year
> When I click on the SELECT BODY icon, nothing happens. In the Report View,
> it display
> "16:22:18  Running the Python command 'body_sel_cmd' failed:
> Traceback (most recent call last):
>   File "D:\FreeCAD_0.19.23463\Mod\MBDyn\MBDyn_guitools\body_AS4_cmd.py",
> line 47, in Activated
>     if check_solid(modbod_sub):
>   File "D:\FreeCAD_0.19.23463\Mod\MBDyn\MBDyn_utilities\MBDyn_funcs.py",
> line 206, in check_solid
>     if sol_obj.Shape.ShapeType == 'Solid' or sol_obj.Shape.ShapeType ==
> 'Compound':
>
> cannot determine type of null shape
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mfasano727/MBDynFCwb/issues/10

Unfortunately the selected body needs to bbe linked to a FreeCad body with
property solid.  so it can calculate center of mass, etc. create your
parts with the part design workbench to e sure.
